FROM python:3.12-slim

WORKDIR /app

COPY pyproject.toml main.py .

RUN pip install uv && uv pip compile pyproject.toml -o requirements.txt
RUN uv pip install -r requirements.txt --system

CMD ["python", "main.py"]
