FROM python:3.12-slim

WORKDIR /app

COPY pyproject.toml .
COPY src/ .

RUN pip install uv && uv pip compile pyproject.toml -o requirements.txt
RUN uv pip install -r requirements.txt --system

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
